"""add igdb metadata columns to video_game

Revision ID: 3db7974d53ec
Revises: bfa8d1e1d974
Create Date: 2026-08-24 13:03:20.333188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's string columns render as sqlmodel.sql.sqltypes.AutoString in
# autogenerated migrations, but Alembic's stock template doesn't import it.
# Added here so every generated migration can actually run.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3db7974d53ec'
down_revision: Union[str, Sequence[str], None] = 'bfa8d1e1d974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_game', sa.Column('igdb_id', sa.Integer(), nullable=True))
    op.add_column('video_game', sa.Column('cover_image_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video_game', sa.Column('esrb_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video_game', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video_game', sa.Column('first_release_date', sa.Date(), nullable=True))
    op.add_column('video_game', sa.Column('max_local_players', sa.Integer(), nullable=True))
    op.add_column('video_game', sa.Column('max_online_players', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_game', 'max_online_players')
    op.drop_column('video_game', 'max_local_players')
    op.drop_column('video_game', 'first_release_date')
    op.drop_column('video_game', 'summary')
    op.drop_column('video_game', 'esrb_rating')
    op.drop_column('video_game', 'cover_image_id')
    op.drop_column('video_game', 'igdb_id')
    # ### end Alembic commands ###
