"""add tag and video_game_tag tables

Revision ID: 4c3feeac245b
Revises: 3db7974d53ec
Create Date: 2026-08-24 13:05:22.393673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's string columns render as sqlmodel.sql.sqltypes.AutoString in
# autogenerated migrations, but Alembic's stock template doesn't import it.
# Added here so every generated migration can actually run.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c3feeac245b'
down_revision: Union[str, Sequence[str], None] = '3db7974d53ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_kind'), 'tag', ['kind'], unique=False)
    op.create_table('video_game_tag',
    sa.Column('video_game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['video_game_id'], ['video_game.id'], ),
    sa.PrimaryKeyConstraint('video_game_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_game_tag')
    op.drop_index(op.f('ix_tag_kind'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
