"""make video_game.platform nullable

Revision ID: 6726983999e4
Revises: 949cb8ed4d8d
Create Date: 2026-09-11 13:02:04.015312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's string columns render as sqlmodel.sql.sqltypes.AutoString in
# autogenerated migrations, but Alembic's stock template doesn't import it.
# Added here so every generated migration can actually run.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6726983999e4'
down_revision: Union[str, Sequence[str], None] = '949cb8ed4d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_game', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Restoring NOT NULL needs every row to have a value, and rows created
    after the upgrade won't — ownership moved to `copy`. So this backfills
    first, and the backfill is lossy on purpose:

    A game owned on three platforms has three copies and one column to put
    them in. We take one (lowest copy id, so the result is at least
    deterministic) and the other two are gone. Games with no copies at all
    get the empty string, because NOT NULL leaves nowhere else to go.

    That loss is inherent to the old shape, not a flaw in the downgrade —
    the single-column schema simply cannot represent owning a game twice.
    """
    op.execute(
        sa.text(
            """
            UPDATE video_game vg
            SET platform = COALESCE(
                (
                    SELECT p.name
                    FROM copy c
                    JOIN platform p ON p.id = c.platform_id
                    WHERE c.video_game_id = vg.id
                    ORDER BY c.id
                    LIMIT 1
                ),
                ''
            )
            WHERE vg.platform IS NULL
            """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_game', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
