"""add platform and copy tables, migrate platform strings

Revision ID: 949cb8ed4d8d
Revises: 4c3feeac245b
Create Date: 2026-09-11 12:22:20.106882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's string columns render as sqlmodel.sql.sqltypes.AutoString in
# autogenerated migrations, but Alembic's stock template doesn't import it.
# Added here so every generated migration can actually run.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '949cb8ed4d8d'
down_revision: Union[str, Sequence[str], None] = '4c3feeac245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('borrowed_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.ForeignKeyConstraint(['video_game_id'], ['video_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_platform_id'), 'copy', ['platform_id'], unique=False)
    op.create_index(op.f('ix_copy_video_game_id'), 'copy', ['video_game_id'], unique=False)
    # ### end Alembic commands ###

    # --- hand-written data movement -------------------------------------
    # Autogenerate cannot produce this: it compares structure, and has no
    # idea that the strings in video_game.platform are supposed to become
    # rows in two new tables.
    #
    # video_game.platform is deliberately LEFT IN PLACE. This is the "expand"
    # half of an expand/contract migration — old and new representations coexist
    # so nothing reading the old column breaks while consumers move over. The
    # column gets dropped in a later migration, once nothing reads it.

    # One platform row per distinct name. trim() guards against " PS5 " and
    # "PS5" becoming two rows; the unique index on name would reject the
    # second anyway, but failing a migration is a worse way to find out.
    op.execute(
        sa.text(
            """
            INSERT INTO platform (name)
            SELECT DISTINCT trim(platform)
            FROM video_game
            WHERE platform IS NOT NULL AND trim(platform) <> ''
            """
        )
    )

    # One copy per existing game, pointing at the platform row just created.
    #
    # access defaults to 'owned': everything already in the library is
    # something Dexter has. format is left NULL on purpose — the old schema
    # recorded the platform and never the medium, so whether a PS5 game is a
    # disc or a download is genuinely unknown. Writing a guess would put data
    # in the database that looks authoritative and isn't.
    op.execute(
        sa.text(
            """
            INSERT INTO copy (video_game_id, platform_id, access, format)
            SELECT vg.id, p.id, 'owned', NULL
            FROM video_game vg
            JOIN platform p ON p.name = trim(vg.platform)
            WHERE vg.platform IS NOT NULL AND trim(vg.platform) <> ''
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema.

    No data reconstruction needed, and that is the whole point of keeping
    video_game.platform: the original column was never touched, so dropping
    these two tables restores the previous state exactly. Copies added after
    the migration are lost, which is correct — the old schema has nowhere to
    put a second copy of a game.

    The lossy reconstruction only becomes a problem in the later migration
    that drops the column.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copy_video_game_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_platform_id'), table_name='copy')
    op.drop_table('copy')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_table('platform')
    # ### end Alembic commands ###
